### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by MaksimKiselev** [sergeymakinen/yii2-telegram-log#2]
Hi, thanks for the extension.

1) What is the meaning of the parameter `enableNotification`?

You can also specify the property `levels` inherited from \yii\log\Logger as array or as bit mask.

2) Maybe provide link to `@get_id_bot` for get `chat_id`, or write own.

**Comment by sergeymakinen** [comment]
Hi there, thank you!

1. It controls a `disable_notification` parameter described [here](https://core.telegram.org/bots/api#sendmessage). It's not related to `levels`. But maybe allowing an array was an overcomplication.
2. Oh, thanks for this! I wasn't aware. I will update readme with `@get_id_bot`.

**Comment by MKiselev** [comment]
@sergeymakinen hi))

Извини, по-русски напишу, в инглишь плохо умею.

Я подумал, можно обязательным параметром сделать только `token` а уже где-либо:
1) Консольный метод, через токен получить updates от api и на все `/start` вернуть `chat_id`
2) При отправке лога в телеграмм проверять задан ли `chat_id` явно, либо есть ли он в кеше, либо получить updates и оттуда выдернуть `chat_id`

Мне нравится больше первый вариант, но оба варианта странные, по тому что придётся к консольному приложению цеплять контроллер,
